// packages/vue/src/components/hud/SoundMeter/SoundMeter.vue
<script lang="ts">
export type SoundLevel = 'low' | 'high'

export interface SoundMeterProps {
  /** 声音等级 */
  level?: SoundLevel
  /** 尺寸（默认 50px） */
  size?: number
}
</script>

<script setup lang="ts">
import { computed } from 'vue'
import styles from '@react/components/hud/SoundMeter/soundMeter.module.less'
import soundBgSvg from '@core/assets/svg/sound-bg.svg'
import soundMeterLowSvg from '@core/assets/svg/sound-meter-low.svg'
import soundMeterHighSvg from '@core/assets/svg/sound-meter-high.svg'

const props = withDefaults(defineProps<SoundMeterProps>(), { level: 'low', size: 50 })
const meter = computed(() => (props.level === 'high' ? soundMeterHighSvg : soundMeterLowSvg))
</script>

<template>
  <div :class="styles.container" :style="{ width: props.size + 'px', height: props.size + 'px' }">
    <img :src="soundBgSvg" alt="" :class="styles.bg" />
    <img :src="meter" alt="" :class="styles.meter" />
  </div>
</template>

// src/components/hud/SoundMeter/SoundMeter.tsx
import React from 'react'
import classNames from 'classnames'
import styles from './soundMeter.module.less'
import soundBgSvg from '../../../assets/svg/sound-bg.svg'
import soundMeterLowSvg from '../../../assets/svg/sound-meter-low.svg'
import soundMeterHighSvg from '../../../assets/svg/sound-meter-high.svg'

export type SoundLevel = 'low' | 'high'

export interface SoundMeterProps {
  level?: SoundLevel
  size?: number
  className?: string
  style?: React.CSSProperties
}

const SoundMeter: React.FC<SoundMeterProps> = ({ level = 'low', size = 50, className, style }) => (
  <div className={classNames(styles.container, className)} style={{ width: size, height: size, ...style }}>
    <img src={soundBgSvg} alt="" className={styles.bg} />
    <img src={level === 'high' ? soundMeterHighSvg : soundMeterLowSvg} alt="" className={styles.meter} />
  </div>
)

SoundMeter.displayName = 'SoundMeter'
export default SoundMeter
