// packages/vue/src/components/Card/Card.vue
<script lang="ts">
export type CardVariant = 'default' | 'sheikah' | 'item' | 'golden'

export interface CardProps {
  /** 卡片变体 */
  variant?: CardVariant
  /** 卡片标题（复杂内容用 #title slot） */
  title?: string
  /** 是否选中 */
  selected?: boolean
}
</script>

<script setup lang="ts">
import styles from '@react/components/Card/card.module.less'

const props = withDefaults(defineProps<CardProps>(), {
  variant: 'default',
  title: undefined,
  selected: false,
})

defineSlots<{
  default?: () => unknown
  /** 标题区（覆盖 title prop） */
  title?: () => unknown
}>()
</script>

<template>
  <div
    :class="[styles.card, styles[props.variant], { [styles.selected]: props.selected }]"
  >
    <div v-if="$slots.title || props.title" :class="styles.title">
      <slot name="title">{{ props.title }}</slot>
    </div>
    <div :class="styles.body"><slot /></div>
  </div>
</template>

// src/components/Card/Card.tsx
import React from 'react'
import classNames from 'classnames'
import styles from './card.module.less'

export type CardVariant = 'default' | 'sheikah' | 'item' | 'golden'

export interface CardProps extends Omit<React.HTMLAttributes<HTMLDivElement>, 'title'> {
  /** 卡片变体 */
  variant?: CardVariant
  /** 卡片标题 */
  title?: React.ReactNode
  /** 是否选中 */
  selected?: boolean
  children?: React.ReactNode
}

const Card: React.FC<CardProps> = ({
  variant = 'default',
  title,
  selected = false,
  children,
  className,
  style,
  ...rest
}) => {
  const cls = classNames(
    styles.card,
    styles[variant],
    { [styles.selected]: selected },
    className
  )

  return (
    <div className={cls} style={style} {...rest}>
      {title && <div className={styles.title}>{title}</div>}
      <div className={styles.body}>{children}</div>
    </div>
  )
}

Card.displayName = 'Card'
export default Card
