// src/components/hud/SheikahAbility/SheikahAbility.tsx
import React from 'react'
import classNames from 'classnames'
import styles from './sheikahAbility.module.less'
import roundBombPlusSvg from '../../../assets/svg/ability-round-bomb-plus.svg'
import roundBombSvg from '../../../assets/svg/ability-round-bomb.svg'
import cubeBombSvg from '../../../assets/svg/ability-cube-bomb.svg'
import cameraSvg from '../../../assets/svg/ability-camera.svg'
import stasisSvg from '../../../assets/svg/ability-stasis.svg'
import cryonisSvg from '../../../assets/svg/ability-cryonis.svg'
import magnesisSvg from '../../../assets/svg/ability-magnesis.svg'

export type AbilityType = 'roundBomb' | 'cubeBomb' | 'magnesis' | 'stasis' | 'cryonis' | 'camera'

export interface SheikahAbilityProps {
  ability: AbilityType
  recharging?: boolean
  plus?: boolean
  size?: number
  className?: string
  style?: React.CSSProperties
}

/** 从 Figma 精确导出的能力图标 SVG */
const ABILITY_SVGS: Record<AbilityType, string> = {
  roundBomb: roundBombSvg,
  cubeBomb: cubeBombSvg,
  magnesis: magnesisSvg,
  stasis: stasisSvg,
  cryonis: cryonisSvg,
  camera: cameraSvg,
}

const ABILITY_PLUS_SVGS: Record<AbilityType, string> = {
  roundBomb: roundBombPlusSvg,
  cubeBomb: cubeBombSvg,
  magnesis: magnesisSvg,
  stasis: stasisSvg,
  cryonis: cryonisSvg,
  camera: cameraSvg,
}

const SheikahAbility: React.FC<SheikahAbilityProps> = ({
  ability, recharging = false, plus = false, size = 70, className, style,
}) => (
  <div
    className={classNames(styles.container, { [styles.recharging]: recharging }, className)}
    style={{ width: size, height: size, ...style }}
  >
    <img
      src={plus ? ABILITY_PLUS_SVGS[ability] : ABILITY_SVGS[ability]}
      alt=""
      className={styles.icon}
    />
    {plus && <span className={styles.plusBadge}>+</span>}
    {recharging && <div className={styles.rechargeOverlay} />}
  </div>
)

SheikahAbility.displayName = 'SheikahAbility'
export default SheikahAbility

// packages/vue/src/components/hud/SheikahAbility/SheikahAbility.vue
<script lang="ts">
export type AbilityType = 'roundBomb' | 'cubeBomb' | 'magnesis' | 'stasis' | 'cryonis' | 'camera'

export interface SheikahAbilityProps {
  /** 能力类型 */
  ability: AbilityType
  /** 是否充能中 */
  recharging?: boolean
  /** 是否 Plus 版本 */
  plus?: boolean
  /** 尺寸（默认 70px） */
  size?: number
}
</script>

<script setup lang="ts">
import { computed } from 'vue'
import styles from '@react/components/hud/SheikahAbility/sheikahAbility.module.less'
import roundBombPlusSvg from '@core/assets/svg/ability-round-bomb-plus.svg'
import roundBombSvg from '@core/assets/svg/ability-round-bomb.svg'
import cubeBombSvg from '@core/assets/svg/ability-cube-bomb.svg'
import cameraSvg from '@core/assets/svg/ability-camera.svg'
import stasisSvg from '@core/assets/svg/ability-stasis.svg'
import cryonisSvg from '@core/assets/svg/ability-cryonis.svg'
import magnesisSvg from '@core/assets/svg/ability-magnesis.svg'

const ABILITY_SVGS: Record<AbilityType, string> = {
  roundBomb: roundBombSvg,
  cubeBomb: cubeBombSvg,
  magnesis: magnesisSvg,
  stasis: stasisSvg,
  cryonis: cryonisSvg,
  camera: cameraSvg,
}
const ABILITY_PLUS_SVGS: Record<AbilityType, string> = {
  roundBomb: roundBombPlusSvg,
  cubeBomb: cubeBombSvg,
  magnesis: magnesisSvg,
  stasis: stasisSvg,
  cryonis: cryonisSvg,
  camera: cameraSvg,
}

const props = withDefaults(defineProps<SheikahAbilityProps>(), { recharging: false, plus: false, size: 70 })
const src = computed(() => (props.plus ? ABILITY_PLUS_SVGS[props.ability] : ABILITY_SVGS[props.ability]))
</script>

<template>
  <div
    :class="[styles.container, { [styles.recharging]: props.recharging }]"
    :style="{ width: props.size + 'px', height: props.size + 'px' }"
  >
    <img :src="src" alt="" :class="styles.icon" />
    <span v-if="props.plus" :class="styles.plusBadge">+</span>
    <div v-if="props.recharging" :class="styles.rechargeOverlay" />
  </div>
</template>
