// packages/vue/src/components/Loading/Loading.vue
<script lang="ts">
export interface LoadingProps {
  /** 加载提示文字 */
  tip?: string
  /** 尺寸 */
  size?: 'small' | 'middle' | 'large'
}
</script>

<script setup lang="ts">
import styles from '@react/components/Loading/loading.module.less'

const props = withDefaults(defineProps<LoadingProps>(), {
  tip: undefined,
  size: 'middle',
})
</script>

<template>
  <div :class="[styles.container, styles[props.size]]">
    <div :class="styles.spinner">
      <div :class="styles.ring" />
      <div :class="styles.eye" />
    </div>
    <span v-if="props.tip" :class="styles.tip">{{ props.tip }}</span>
  </div>
</template>

// src/components/Loading/Loading.tsx
import React from 'react'
import classNames from 'classnames'
import styles from './loading.module.less'

export interface LoadingProps {
  /** 加载提示文字 */
  tip?: string
  /** 尺寸 */
  size?: 'small' | 'middle' | 'large'
  /** 自定义类名 */
  className?: string
  /** 自定义样式 */
  style?: React.CSSProperties
}

const Loading: React.FC<LoadingProps> = ({
  tip,
  size = 'middle',
  className,
  style,
}) => {
  return (
    <div className={classNames(styles.container, styles[size], className)} style={style}>
      <div className={styles.spinner}>
        <div className={styles.ring} />
        <div className={styles.eye} />
      </div>
      {tip && <span className={styles.tip}>{tip}</span>}
    </div>
  )
}

Loading.displayName = 'Loading'
export default Loading
