// packages/vue/src/components/Dialog/Dialog.vue
<script lang="ts">
export type DialogType = 'speech' | 'written' | 'sheikah'

export interface DialogProps {
  /** 对话框类型 */
  type?: DialogType
  /** 说话人名字 */
  speaker?: string
  /** 是否显示继续箭头 */
  showContinue?: boolean
}

/** 从 Figma 导出的精确对话框背景路径（与 React 版同源） */
const DIALOG_BG_PATH = "M0 90C0 40.2944 40.2944 0 90 0H820C869.706 0 910 40.2944 910 90V95C910 144.706 869.706 185 820 185H90C40.2944 185 0 144.706 0 95V90ZM21.8372 85.7898C21.7117 86.7497 22.4442 87.5827 23.3745 87.5827H24.385C25.2104 87.5827 25.894 86.9212 25.9877 86.0673C26.9015 77.7396 30.0223 70.1101 34.7259 63.8289C35.513 62.7778 34.4479 61.384 33.5138 62.2951C27.2995 68.3565 23.0426 76.5678 21.8372 85.7898ZM21.8437 99.3087C21.6896 98.3355 22.4273 97.4734 23.3745 97.4734H24.3603C25.1713 97.4734 25.8479 98.1128 25.9585 98.9494C27.0069 106.881 30.0623 114.146 34.5738 120.171C35.3609 121.222 34.2958 122.616 33.3616 121.705C27.3951 115.885 23.2331 108.084 21.8437 99.3087ZM23.0253 89.9675C23.4158 89.5769 24.0489 89.5769 24.4395 89.9675L26.293 91.821C26.6835 92.2115 26.6835 92.8447 26.293 93.2352L24.4395 95.0888C24.0489 95.4793 23.4158 95.4793 23.0253 95.0888L21.1717 93.2352C20.7812 92.8447 20.7812 92.2115 21.1717 91.821L23.0253 89.9675ZM886.625 86.5266C887.573 86.5266 888.31 85.6645 888.156 84.6913C886.767 75.9163 882.605 68.1148 876.638 62.2951C875.704 61.384 874.639 62.7778 875.426 63.8288C879.938 69.8535 882.993 77.1187 884.042 85.0506C884.152 85.8872 884.829 86.5266 885.64 86.5266H886.625ZM886.625 96.4173C887.556 96.4173 888.288 97.2503 888.163 98.2102C886.957 107.432 882.701 115.644 876.486 121.705C875.552 122.616 874.487 121.222 875.274 120.171C879.978 113.89 883.098 106.26 884.012 97.9327C884.106 97.0788 884.79 96.4173 885.615 96.4173H886.625ZM885.561 94.0325C885.951 94.4231 886.584 94.4231 886.975 94.0325L888.828 92.179C889.219 91.7885 889.219 91.1553 888.828 90.7648L886.975 88.9112C886.584 88.5207 885.951 88.5207 885.561 88.9112L883.707 90.7648C883.316 91.1553 883.316 91.7885 883.707 92.179L885.561 94.0325Z"

/** 外层胶囊轮廓（sheikah 变体的描边） */
const DIALOG_OUTLINE_PATH = "M0 90C0 40.2944 40.2944 0 90 0H820C869.706 0 910 40.2944 910 90V95C910 144.706 869.706 185 820 185H90C40.2944 185 0 144.706 0 95V90Z"
</script>

<script setup lang="ts">
import { computed } from 'vue'
import styles from '@react/components/Dialog/dialog.module.less'

const props = withDefaults(defineProps<DialogProps>(), {
  type: 'speech',
  speaker: undefined,
  showContinue: true,
})

const ariaLabel = computed(() => (props.speaker ? `${props.speaker} dialog` : 'Dialog'))
</script>

<template>
  <div
    :class="[styles.dialog, styles[props.type]]"
    role="region"
    :aria-label="ariaLabel"
  >
    <svg :class="styles.bg" viewBox="0 0 910 185" fill="none" preserveAspectRatio="none" aria-hidden="true">
      <path fill-rule="evenodd" clip-rule="evenodd" :d="DIALOG_BG_PATH" fill="black" fill-opacity="0.5" />
      <path
        v-if="props.type === 'sheikah'"
        :d="DIALOG_OUTLINE_PATH"
        fill="none"
        stroke="rgba(60,211,252,0.6)"
        stroke-width="1.5"
        vector-effect="non-scaling-stroke"
      />
    </svg>
    <div v-if="props.speaker" :class="styles.speaker">{{ props.speaker }}</div>
    <div :class="styles.content"><slot /></div>
    <span v-if="props.showContinue" :class="styles.continueArrow" aria-hidden="true">
      <svg aria-hidden="true" width="40" height="26" viewBox="0 0 38 25.4" fill="none">
        <path d="M19 25.4L0 6.4L6.4 0L19 12.6L31.6 0L38 6.4L19 25.4Z" fill="rgba(226,222,211,0.5)" />
      </svg>
    </span>
  </div>
</template>

// src/components/Dialog/Dialog.tsx
import React from 'react'
import classNames from 'classnames'
import styles from './dialog.module.less'

export type DialogType = 'speech' | 'written' | 'sheikah'
export interface DialogProps { type?: DialogType; speaker?: string; children?: React.ReactNode; showContinue?: boolean; className?: string; style?: React.CSSProperties }

const DIALOG_BG_PATH = "M0 90C0 40.2944 40.2944 0 90 0H820C869.706 0 910 40.2944 910 90V95C910 144.706 869.706 185 820 185H90C40.2944 185 0 144.706 0 95V90ZM21.8372 85.7898C21.7117 86.7497 22.4442 87.5827 23.3745 87.5827H24.385C25.2104 87.5827 25.894 86.9212 25.9877 86.0673C26.9015 77.7396 30.0223 70.1101 34.7259 63.8289C35.513 62.7778 34.4479 61.384 33.5138 62.2951C27.2995 68.3565 23.0426 76.5678 21.8372 85.7898ZM21.8437 99.3087C21.6896 98.3355 22.4273 97.4734 23.3745 97.4734H24.3603C25.1713 97.4734 25.8479 98.1128 25.9585 98.9494C27.0069 106.881 30.0623 114.146 34.5738 120.171C35.3609 121.222 34.2958 122.616 33.3616 121.705C27.3951 115.885 23.2331 108.084 21.8437 99.3087ZM23.0253 89.9675C23.4158 89.5769 24.0489 89.5769 24.4395 89.9675L26.293 91.821C26.6835 92.2115 26.6835 92.8447 26.293 93.2352L24.4395 95.0888C24.0489 95.4793 23.4158 95.4793 23.0253 95.0888L21.1717 93.2352C20.7812 92.8447 20.7812 92.2115 21.1717 91.821L23.0253 89.9675ZM886.625 86.5266C887.573 86.5266 888.31 85.6645 888.156 84.6913C886.767 75.9163 882.605 68.1148 876.638 62.2951C875.704 61.384 874.639 62.7778 875.426 63.8288C879.938 69.8535 882.993 77.1187 884.042 85.0506C884.152 85.8872 884.829 86.5266 885.64 86.5266H886.625ZM886.625 96.4173C887.556 96.4173 888.288 97.2503 888.163 98.2102C886.957 107.432 882.701 115.644 876.486 121.705C875.552 122.616 874.487 121.222 875.274 120.171C879.978 113.89 883.098 106.26 884.012 97.9327C884.106 97.0788 884.79 96.4173 885.615 96.4173H886.625ZM885.561 94.0325C885.951 94.4231 886.584 94.4231 886.975 94.0325L888.828 92.179C889.219 91.7885 889.219 91.1553 888.828 90.7648L886.975 88.9112C886.584 88.5207 885.951 88.5207 885.561 88.9112L883.707 90.7648C883.316 91.1553 883.316 91.7885 883.707 92.179L885.561 94.0325Z"

const Dialog: React.FC<DialogProps> = ({ type = 'speech', speaker, children, showContinue = true, className, style }) => (
  <div className={classNames(styles.dialog, styles[type], className)} style={style} role="region" aria-label={speaker ? `${speaker} dialog` : 'Dialog'}>
    <svg className={styles.bg} viewBox="0 0 910 185" fill="none" preserveAspectRatio="none" aria-hidden="true"><path fillRule="evenodd" clipRule="evenodd" d={DIALOG_BG_PATH} fill="black" fillOpacity="0.5" /></svg>
    {speaker && <div className={styles.speaker}>{speaker}</div>}
    <div className={styles.content}>{children}</div>
    {showContinue && <span className={styles.continueArrow} aria-hidden="true"><svg width="40" height="26" viewBox="0 0 38 25.4" fill="none"><path d="M19 25.4L0 6.4L6.4 0L19 12.6L31.6 0L38 6.4L19 25.4Z" fill="rgba(226,222,211,0.5)" /></svg></span>}
  </div>
)

Dialog.displayName = 'Dialog'
export default Dialog
