// src/components/hud/HorseSpur/HorseSpur.tsx
import React from 'react'
import classNames from 'classnames'
import styles from './horseSpur.module.less'
import horseSpurNormalSvg from '../../../assets/svg/horse-spur-normal.svg'

export type HorseSpurVariant = 'normal' | 'ancient' | 'endura'

export interface HorseSpurProps {
  /** 冲刺类型 */
  type?: HorseSpurVariant
  /** 是否已使用 */
  used?: boolean
  /** 尺寸（默认 84px） */
  size?: number
  className?: string
  style?: React.CSSProperties
}

const HorseSpur: React.FC<HorseSpurProps> = ({ type = 'normal', used = false, size = 84, className, style }) => (
  <div
    className={classNames(styles.container, styles[type], { [styles.used]: used }, className)}
    style={{ width: size, height: size, ...style }}
  >
    <img src={horseSpurNormalSvg} alt="" className={styles.icon} />
  </div>
)

HorseSpur.displayName = 'HorseSpur'
export default HorseSpur

// packages/vue/src/components/hud/HorseSpur/HorseSpur.vue
<script lang="ts">
export type HorseSpurVariant = 'normal' | 'ancient' | 'endura'

export interface HorseSpurProps {
  /** 冲刺类型 */
  type?: HorseSpurVariant
  /** 是否已使用 */
  used?: boolean
  /** 尺寸（默认 84px） */
  size?: number
}
</script>

<script setup lang="ts">
import styles from '@react/components/hud/HorseSpur/horseSpur.module.less'
import horseSpurNormalSvg from '@core/assets/svg/horse-spur-normal.svg'

const props = withDefaults(defineProps<HorseSpurProps>(), { type: 'normal', used: false, size: 84 })
</script>

<template>
  <div
    :class="[styles.container, styles[props.type], { [styles.used]: props.used }]"
    :style="{ width: props.size + 'px', height: props.size + 'px' }"
  >
    <img :src="horseSpurNormalSvg" alt="" :class="styles.icon" />
  </div>
</template>
